packages:
  - 'packages/*'
  # Services will be added here by create-service script
  # Example:
  # - 'agents'
  # - 'workflows'
  # - 'stripe'
  - 'auth'
  - 'things'
  - 'domains'
  # SDK packages (for domains.do types)
  - '../sdk/packages/*'
