packages:
  - 'apps/*'
  - 'workers/*'
  - 'middleware/*'
  - 'objects/*'
  - 'snippets/*'
  - 'packages/*'
  - 'sdks/*'
  - 'startups/*'
  - 'integrations/*'
  - 'auth/*'
  - 'plugins/*'
  - 'primitives/packages/*'
