packages:
  - 'packages/*'
  # All worker services
  - 'embeddings'
  - 'auth'
  - 'things'
  - 'domains'
  # SDK packages (foundation packages)
  - '../sdk/packages/ai-embeddings'
  - '../sdk/packages/ai-chat'
  - '../sdk/packages/ai-agents'
  - '../sdk/packages/ai-tools'
  - '../sdk/packages/*'
