packages:
  - 'packages/*'
  # All worker services
  - 'ai'
  - 'embeddings'
  - 'auth'
  - 'things'
  - 'domains'
  - 'dns-tools'
  - 'domain-monitor'
  - 'analytics'
  - 'numerics'
  - 'seo-crawler'
  - 'seo-schema'
  - 'seo-content'
  - 'seo-performance'
  - 'seo-tools'
  - 'seo-admin'
  - 'veo'
  - 'imagen'
  - 'voice'
  - 'podcast'
  - 'email-validation'
  - 'esp-gateway'
  - 'email-sender'
  - 'email-campaigns'
  - 'email-warming'
  - 'deliverability'
  - 'blacklist-monitor'
  - 'lead-enrichment'
  - 'ads-campaigns'
  # SDK packages (foundation packages)
  - '../sdk/packages/ai-generation'
  - '../sdk/packages/ai-embeddings'
  - '../sdk/packages/ai-chat'
  - '../sdk/packages/ai-models'
  - '../sdk/packages/ai-agents'
  - '../sdk/packages/ai-tools'
  - '../sdk/packages/*'
