/**
 * Integration tests for SEO Crawler Worker
 */

import { describe, it, expect, beforeAll } from 'vitest'

describe('SEO Crawler Integration Tests', () => {
  const baseUrl = process.env.SEO_CRAWLER_URL || 'http://localhost:8787'

  it('should detect ChatGPT-User bot', async () => {
    const response = await fetch(`${baseUrl}/detect`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        userAgent: 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko); compatible; ChatGPT-User/1.0; +https://openai.com/bot',
      }),
    })

    expect(response.status).toBe(200)
    const data = await response.json()
    expect(data.isBot).toBe(true)
    expect(data.botType).toBe('ChatGPT-User/2.0')
    expect(data.botPurpose).toBe('live_retrieval')
  })

  it('should detect ClaudeBot', async () => {
    const response = await fetch(`${baseUrl}/detect`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        userAgent: 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko); compatible; ClaudeBot/1.0; +claudebot@anthropic.com',
      }),
    })

    expect(response.status).toBe(200)
    const data = await response.json()
    expect(data.isBot).toBe(true)
    expect(data.botType).toBe('ClaudeBot')
    expect(data.botPurpose).toBe('training')
  })

  it('should generate robots.txt', async () => {
    const response = await fetch(`${baseUrl}/robots.txt`)

    expect(response.status).toBe(200)
    expect(response.headers.get('content-type')).toBe('text/plain')

    const content = await response.text()
    expect(content).toContain('User-agent:')
    expect(content).toContain('# robots.txt generated by SEO Crawler Service')
  })

  it('should create and retrieve bot access rule', async () => {
    // Create rule
    const rule = {
      userAgent: 'TestBot',
      access: 'allow',
      paths: ['/api/*'],
      priority: 100,
      reason: 'Test rule',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }

    const createResponse = await fetch(`${baseUrl}/rules`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(rule),
    })

    expect(createResponse.status).toBe(200)

    // Retrieve rule
    const getResponse = await fetch(`${baseUrl}/rules/TestBot`)
    expect(getResponse.status).toBe(200)

    const retrievedRule = await getResponse.json()
    expect(retrievedRule.userAgent).toBe('TestBot')
    expect(retrievedRule.access).toBe('allow')
  })
})
